import { invoke } from "@tauri-apps/api/core";
import type { FanFanBridge, SearchRequest } from "./contracts";

export const tauriBridge: FanFanBridge = {
  startup_get_state: () => invoke("startup_get_state"),
  welcome_get_state: () => invoke("welcome_get_state"),
  welcome_complete: (welcome_version) => invoke("welcome_complete", { request: { welcome_version } }),
  welcome_authorization_complete: () => invoke("welcome_authorization_complete"),
  theme_get_state: (system_dark) => invoke("theme_get_state", { request: { system_dark } }),
  theme_set_preference: (preference, system_dark) => invoke("theme_set_preference", { request: { preference, system_dark } }),
  environment_get_latest: () => invoke("environment_get_latest"),
  environment_detect: () => invoke("environment_detect"),
  model_state_get: () => invoke("model_state_get"),
  model_import_scan: (paths) => invoke("model_import_scan", { request: { paths } }),
  model_import_confirm: (selections) => invoke("model_import_confirm", { request: { selections } }),
  model_artifact_list: () => invoke("model_artifact_list"),
  model_role_config_list: () => invoke("model_role_config_list"),
  model_catalog_list: (source) => invoke("model_catalog_list", { source }),
  model_role_catalog_list: () => invoke("model_role_catalog_list"),
  model_preset_list: () => invoke("model_preset_list"),
  model_download_start: (edition_id, source, confirmed) => invoke("model_download_start", { request: { edition_id, source, confirmed } }),
  model_download_list: () => invoke("model_download_list"),
  model_store_status_get: () => invoke("model_store_status_get"),
  model_download_get: (job_id) => invoke("model_download_get", { request: { job_id } }),
  model_download_pause: (job_id) => invoke("model_download_pause", { request: { job_id } }),
  model_download_cancel: (job_id) => invoke("model_download_cancel", { request: { job_id } }),
  model_download_resume: (job_id) => invoke("model_download_resume", { request: { job_id } }),
  model_download_retry: (job_id) => invoke("model_download_retry", { request: { job_id } }),
  model_download_switch_source: (job_id, source) => invoke("model_download_switch_source", { request: { job_id, source } }),
  model_download_remove: (job_id) => invoke("model_download_remove", { request: { job_id } }),
  model_artifact_activate: (artifact_id) => invoke("model_artifact_activate", { request: { artifact_id } }),
  model_role_disable: (role) => invoke("model_role_disable", { request: { role } }),
  home_get_summary: (local_date) => invoke("home_get_summary", { request: { local_date } }),
  candidate_root_action: (candidate_id, action) => invoke("candidate_root_action", { request: { candidate_id, action } }),
  search_start: (request: SearchRequest) => invoke("search_start", { request }),
  rag_readiness_get: (scope) => invoke("rag_readiness_get", { request: { scope } }),
  ask_start: (request) => invoke("ask_start", { request }),
  ask_session_query: (cursor = null, page_size = 30) => invoke("ask_session_query", { request: { cursor, page_size } }),
  ask_message_query: (session_id, cursor = null, page_size = 100) => invoke("ask_message_query", { request: { session_id, cursor, page_size } }),
  ask_session_rename: (session_id, title) => invoke("ask_session_rename", { request: { session_id, title } }),
  ask_session_delete: (session_id) => invoke("ask_session_delete", { request: { session_id } }),
  ask_operation_get: (operation_id) => invoke("ask_operation_get", { request: { operation_id } }),
  ask_cancel: (operation_id) => invoke("ask_cancel", { request: { operation_id } }),
  speech_recognize: (request) => invoke("speech_recognize", { request }),
  speech_synthesize_answer: (message_id, speed, speaker_id = 0) => invoke("speech_synthesize_answer", { request: { message_id, speed, speaker_id } }),
  answer_export: (message_id, target_path, format, confirmation) => invoke("answer_export", { request: { message_id, target_path, format, confirmation } }),
  preview_get: (file_id, offset = 0, limit = 80, anchor_node_id = null) => invoke("preview_get", { request: { file_id, offset, limit, anchor_node_id } }),
  file_open: (file_id) => invoke("file_open", { request: { file_id } }),
  file_reveal: (file_id) => invoke("file_reveal", { request: { file_id } }),
  inbox_query: (request) => invoke("inbox_query", { request }),
  inbox_update: (inbox_id, triage_status) => invoke("inbox_update", { request: { inbox_id, triage_status } }),
  inbox_retry: (inbox_id) => invoke("inbox_retry", { request: { inbox_id } }),
  ocr_retry: (file_id) => invoke("ocr_retry", { request: { file_id } }),
  image_understanding_retry: (asset_id) => invoke("image_understanding_retry", { request: { asset_id } }),
  image_deep_analyze: (asset_id, question) => invoke("image_deep_analyze", { request: { asset_id, question } }),
  collection_list: () => invoke("collection_list"),
  collection_create: (request) => invoke("collection_create", { request }),
  collection_update: (collection_id, collection) => invoke("collection_update", { request: { collection_id, collection } }),
  collection_delete: (collection_id) => invoke("collection_delete", { request: { collection_id } }),
  collection_rule_preview: (rule, limit) => invoke("collection_rule_preview", { request: { rule, limit } }),
  collection_file_query: (collection_id, request) => invoke("collection_file_query", { request: { collection_id, ...request } }),
  collection_add_file: (collection_id, file_id) => invoke("collection_add_file", { request: { collection_id, file_id } }),
  collection_remove_file: (collection_id, file_id) => invoke("collection_remove_file", { request: { collection_id, file_id } }),
  collection_suggestion_refresh: (max_files = 500) => invoke("collection_suggestion_refresh", { request: { max_files } }),
  collection_suggestion_query: (cursor, page_size, status = "suggested") => invoke("collection_suggestion_query", { request: { cursor, page_size, status } }),
  collection_suggestion_update: (suggestion_id, suggestion) => invoke("collection_suggestion_update", { request: { suggestion_id, suggestion } }),
  collection_suggestion_confirm: (suggestion_id) => invoke("collection_suggestion_confirm", { request: { suggestion_id } }),
  collection_suggestion_reject: (suggestion_id) => invoke("collection_suggestion_reject", { request: { suggestion_id } }),
  relation_refresh: (max_files) => invoke("relation_refresh", { request: { max_files } }),
  relation_query: (request) => invoke("relation_query", { request }),
  relation_review: (relation_id, action) => invoke("relation_review", { request: { relation_id, action } }),
  relation_batch_review: (relation_ids, action) => invoke("relation_batch_review", { request: { relation_ids, action } }),
  relation_group_query: (request) => invoke("relation_group_query", { request }),
  relation_group_review: (group_id, action) => invoke("relation_group_review", { request: { group_id, action } }),
  relation_group_batch_review: (group_ids, action) => invoke("relation_group_batch_review", { request: { group_ids, action } }),
  file_query: (request) => invoke("file_query", { request }),
  exclusion_rule_list: () => invoke("exclusion_rule_list"),
  exclusion_rule_upsert: (request) => invoke("exclusion_rule_upsert", { request }),
  exclusion_rule_delete: (rule_id) => invoke("exclusion_rule_delete", { request: { rule_id } }),
  app_status_get: () => invoke("app_status_get"),
  runtime_state_get: () => invoke("runtime_state_get"),
  maintenance_get: () => invoke("maintenance_get"),
  maintenance_check: (level) => invoke("maintenance_check", { request: { level } }),
  storage_usage_get: () => invoke("storage_usage_get"),
  storage_location_get: () => invoke("storage_location_get"),
  storage_migration_schedule: (selected_directory, confirmation) => invoke("storage_migration_schedule", { request: { selected_directory, confirmation } }),
  cache_clear: (category, confirmation) => invoke("cache_clear", { request: { category, confirmation } }),
  app_data_reset_schedule: (confirmation) => invoke("app_data_reset_schedule", { request: { confirmation } }),
  maintenance_log_query: (request) => invoke("maintenance_log_query", { request }),
  maintenance_logs_clear: () => invoke("maintenance_logs_clear"),
  node_trace_query: (request) => invoke("node_trace_query", { request }),
  node_trace_clear: () => invoke("node_trace_clear"),
  diagnostic_event_append: (request) => invoke("diagnostic_event_append", { request }),
  diagnostic_export: (target_path, confirmed) => invoke("diagnostic_export", { request: { target_path, confirmed } }),
  index_rebuild: (confirmation) => invoke("index_rebuild", { request: { confirmation } }),
  root_list: () => invoke("root_list"),
  root_add: (request) => invoke("root_add", { request }),
  root_disable: (root_id) => invoke("root_disable", { request: { root_id } }),
  scan_start: (root_id, reason) => invoke("scan_start", { request: { root_id, reason } }),
  scan_pause: (job_id) => invoke("scan_pause", { request: { job_id } }),
  scan_resume: (job_id) => invoke("scan_resume", { request: { job_id } }),
  scan_cancel: (job_id) => invoke("scan_cancel", { request: { job_id } }),
};
