import { invoke } from "@tauri-apps/api/core";
import type { ReminBridge, SearchRequest } from "./contracts";

export const tauriBridge: ReminBridge = {
  startup_get_state: () => invoke("startup_get_state"),
  welcome_get_state: () => invoke("welcome_get_state"),
  welcome_complete: (welcome_version) => invoke("welcome_complete", { request: { welcome_version } }),
  environment_get_latest: () => invoke("environment_get_latest"),
  environment_detect: () => invoke("environment_detect"),
  model_state_get: () => invoke("model_state_get"),
  model_import_scan: (paths) => invoke("model_import_scan", { request: { paths } }),
  model_import_confirm: (selections) => invoke("model_import_confirm", { request: { selections } }),
  model_artifact_list: () => invoke("model_artifact_list"),
  model_catalog_list: () => invoke("model_catalog_list"),
  model_download_install: (edition_id, source, confirmed) => invoke("model_download_install", { request: { edition_id, source, confirmed } }),
  model_artifact_activate: (artifact_id) => invoke("model_artifact_activate", { request: { artifact_id } }),
  home_get_summary: (local_date) => invoke("home_get_summary", { request: { local_date } }),
  candidate_root_action: (candidate_id, action) => invoke("candidate_root_action", { request: { candidate_id, action } }),
  search_start: (request: SearchRequest) => invoke("search_start", { request }),
  ask_start: (request) => invoke("ask_start", { request }),
  ask_operation_get: (operation_id) => invoke("ask_operation_get", { request: { operation_id } }),
  ask_cancel: (operation_id) => invoke("ask_cancel", { request: { operation_id } }),
  preview_get: (file_id, offset = 0, limit = 80, anchor_node_id = null) => invoke("preview_get", { request: { file_id, offset, limit, anchor_node_id } }),
  file_open: (file_id) => invoke("file_open", { request: { file_id } }),
  file_reveal: (file_id) => invoke("file_reveal", { request: { file_id } }),
  inbox_query: (request) => invoke("inbox_query", { request }),
  inbox_update: (inbox_id, triage_status) => invoke("inbox_update", { request: { inbox_id, triage_status } }),
  ocr_retry: (file_id) => invoke("ocr_retry", { request: { file_id } }),
  collection_list: () => invoke("collection_list"),
  collection_create: (request) => invoke("collection_create", { request }),
  collection_update: (collection_id, collection) => invoke("collection_update", { request: { collection_id, collection } }),
  collection_delete: (collection_id) => invoke("collection_delete", { request: { collection_id } }),
  collection_rule_preview: (rule, limit) => invoke("collection_rule_preview", { request: { rule, limit } }),
  collection_file_query: (collection_id, request) => invoke("collection_file_query", { request: { collection_id, ...request } }),
  collection_add_file: (collection_id, file_id) => invoke("collection_add_file", { request: { collection_id, file_id } }),
  collection_remove_file: (collection_id, file_id) => invoke("collection_remove_file", { request: { collection_id, file_id } }),
  relation_refresh: (max_files) => invoke("relation_refresh", { request: { max_files } }),
  relation_query: (request) => invoke("relation_query", { request }),
  relation_review: (relation_id, action) => invoke("relation_review", { request: { relation_id, action } }),
  file_query: (request) => invoke("file_query", { request }),
  extraction_preset_list: () => invoke("extraction_preset_list"),
  extraction_run: (file_ids, preset_id) => invoke("extraction_run", { request: { file_ids, preset_id } }),
  skill_list: () => invoke("skill_list"),
  task_plan: (skill_id, file_ids, parameters, user_instruction = null) => invoke("task_plan", { request: { skill_id, file_ids, parameters, user_instruction } }),
  task_execute: (skill_id, file_ids, parameters, planned_task_id, user_instruction = null) => invoke("task_execute", { request: { task_id: planned_task_id, skill_id, file_ids, parameters, user_instruction } }),
  task_recoverable: () => invoke("task_recoverable"),
  task_resume: (task_id) => invoke("task_resume", { request: { task_id } }),
  extraction_export: (run, format, target_path) => invoke("extraction_export", { request: { run, format, target_path } }),
  maintenance_get: () => invoke("maintenance_get"),
  maintenance_check: (level) => invoke("maintenance_check", { request: { level } }),
  maintenance_log_query: (request) => invoke("maintenance_log_query", { request }),
  maintenance_logs_clear: () => invoke("maintenance_logs_clear"),
  diagnostic_export: (target_path, confirmed) => invoke("diagnostic_export", { request: { target_path, confirmed } }),
  index_rebuild: (confirmation) => invoke("index_rebuild", { request: { confirmation } }),
  root_discover_defaults: () => invoke("root_discover_defaults"),
  root_list: () => invoke("root_list"),
  root_add: (request) => invoke("root_add", { request }),
  root_disable: (root_id) => invoke("root_disable", { request: { root_id } }),
  scan_start: (root_id, reason) => invoke("scan_start", { request: { root_id, reason } }),
  scan_pause: (job_id) => invoke("scan_pause", { request: { job_id } }),
  scan_resume: (job_id) => invoke("scan_resume", { request: { job_id } }),
  scan_cancel: (job_id) => invoke("scan_cancel", { request: { job_id } }),
};
