[package]
name = "remin-desktop"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[lib]
name = "remin_desktop_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
chrono.workspace = true
remin-core = { path = "../../../crates/core" }
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
tauri = { version = "2", features = [] }
tauri-plugin-dialog = "2"
tauri-plugin-single-instance = "2"
uuid.workspace = true
windows.workspace = true

[dev-dependencies]
tempfile = "3"
